### ISSUE TITLE
Searching Vehicles

### ISSUE THREAD

**Issue by TheCrypticOG** [GouveiaXS/angelicxs-policeK9#2]
QBCORE
Everytime the dog searches a vehicle it comes back as it doesnt find anything even though there are illegal items specified in the config in the vehicle.

**Comment by GouveiaXS** [comment]
Please ensure that lines 79 and 102 are pointed to the correct inventory table in your database.

line 79        local result = MySQL.Sync.fetchScalar('SELECT items FROM gloveboxitems WHERE plate = ?', {plate})
line 102      local result = MySQL.Sync.fetchScalar('SELECT items FROM trunkitems WHERE plate = ?', {plate})
