### ISSUE TITLE
Dog dying

### ISSUE THREAD

**Issue by danx30** [GouveiaXS/angelicxs-policeK9#3]
If I fire my weapon during a vehicle chase, the dog will jump out of the car and die.

**Comment by GouveiaXS** [comment]
Unable to replicate, please provide further information and/or a video.

**Comment by danx30** [comment]
It's actually whenever I point a weapon at anyone from inside a vehicle, even locals, the dog will jump out and get hurt then run away, or he will die if I'm driving very fast.  I'll get a video clip for you in a little while.  Also I want to be able to get the dog to ride in a 2 door vehicle.

**Comment by danx30** [comment]
Here are two clips.  When in a car, I point my weapon and the dog attacks, that's why he's jumping out.  On foot, I point my weapon he acts like he will attack, but doesn't, however if I hit the attack key he will still attack as normal.

https://medal.tv/games/gta-v/clips/ZLALw4ZG3VfrH/d1337LBz39IY?invite=cr-MSwzOWIsNzA0NDQ0NzUs
https://medal.tv/games/gta-v/clips/ZLBtWcAvzdetZ/d1337eUW2t48?invite=cr-MSw5b0IsNzA0NDQ0NzUs

**Comment by GouveiaXS** [comment]
Issue most likely resolved in releases since.
